# Generated by Django 5.0.6 on 2026-07-13 20:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicianProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('specialization', models.CharField(blank=True, max_length=100)),
                ('experience_years', models.PositiveIntegerField(blank=True, null=True)),
                ('service_area', models.CharField(blank=True, max_length=150)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='technicians/profile_images/')),
                ('license_number', models.CharField(blank=True, max_length=50)),
                ('license_document', models.FileField(blank=True, null=True, upload_to='technicians/licenses/')),
                ('pan_number', models.CharField(blank=True, max_length=10)),
                ('pan_card_document', models.FileField(blank=True, null=True, upload_to='technicians/pan_cards/')),
                ('certification_document', models.FileField(blank=True, null=True, upload_to='technicians/certifications/')),
                ('verification_status', models.CharField(choices=[('NOT_SUBMITTED', 'Not Submitted'), ('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='NOT_SUBMITTED', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_technicians', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='technician_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Technician Profile',
                'verbose_name_plural': 'Technician Profiles',
                'db_table': 'technician_profiles',
            },
        ),
    ]
