# Generated by Django 5.0.6 on 2026-07-14 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
        ('technicians', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicianprofile',
            name='specialization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technicians', to='services.servicecategory'),
        ),
    ]
