# Generated by Django 5.0.6 on 2026-07-18 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technicians', '0002_alter_technicianprofile_specialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicianprofile',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
