# Generated by Django 5.0.6 on 2026-07-25 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technicians', '0004_technicianprofile_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicianprofile',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
