# Generated by Django 5.0.6 on 2026-07-20 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='rental_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='rental_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
