# Generated by Django 5.0.6 on 2026-07-12 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_is_two_factor_enabled_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('can_enable_2fa', 'Can enable two-factor authentication')], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
