# Generated by Django 5.0.6 on 2026-07-27 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0004_listing_latitude_listing_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_text', models.TextField()),
                ('vector', models.JSONField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='listings.listing')),
            ],
        ),
    ]
