# Generated by Django 5.0.6 on 2026-07-20 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='full_name',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='phone_number',
            field=models.CharField(default='exit', max_length=20),
            preserve_default=False,
        ),
    ]
