# Generated by Django 5.0.6 on 2026-07-25 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_servicerequest_current_tech_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='current_tech_latitude',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='current_tech_longitude',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='user_latitude',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='user_longitude',
        ),
    ]
