# Generated by Django 5.0.6 on 2026-07-26 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_servicerequest_work_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('ARRIVED', 'Arrived'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('PAID', 'Paid'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
