# Generated by Django 5.0.6 on 2026-07-26 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_servicerequest_email_alter_servicerequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
